// <auto-generated />
namespace Innlevering_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangesiBlogclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangesiBlogclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201509181042411_Changes i Blog class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
